# trigger:
#   branches:
#     exclude:
#       - "*"
#   tags:
#     include:
#       - "*.*.*"

# pr:
#   branches:
#     exclude:
#       - "*"

jobs:
  - job: ManyLinux

    pool:
      vmImage: "ubuntu-16.04"

    strategy:
      matrix:
        manylinux2010:
          DOCKER_IMAGE: quay.io/pypa/manylinux2010_x86_64
          PLAT: manylinux2010_x86_64

    steps:
      - checkout: self
        submodules: recursive

      - task: DownloadSecureFile@1
        name: pypirc
        inputs:
          secureFile: pivarski-pypirc

      - script: |
          python setup.py sdist
          docker pull $(DOCKER_IMAGE)
          docker run -e PLAT=$(PLAT) -v `pwd`:/io $(DOCKER_IMAGE) /io/.ci/linux-build.sh
          twine upload dist/* --config $(pypirc.secureFilePath)
