trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - "*.*.*"

pr:
  branches:
    exclude:
      - "*"

jobs:
  - job: ManyLinux

    pool:
      vmImage: "ubuntu-16.04"

    steps:
      - checkout: self
        submodules: recursive

