# trigger:
#   branches:
#     exclude:
#       - "*"
#   tags:
#     include:
#       - "*.*.*"

# pr:
#   branches:
#     exclude:
#       - "*"

jobs:
  - job: ManyLinux

    pool:
      vmImage: "ubuntu-16.04"

    strategy:
      matrix:
        manylinux2010:
          DOCKER_IMAGE: quay.io/pypa/manylinux2010_x86_64
          PLAT: manylinux2010_x86_64

    steps:
      - checkout: self
        submodules: recursive

      - task: DownloadSecureFile@1
        name: pypirc
        inputs:
          secureFile: pivarski-pypirc
        displayName: "Credentials"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.7"
          architecture: "x64"
        displayName: "Python 3.7 for twine"

      - script: |
          python -m pip install --upgrade pip
          python -m pip install twine
          docker pull $(DOCKER_IMAGE)
        displayName: "Install"

      - script: |
          python setup.py sdist
          docker run -e PLAT=$(PLAT) -v `pwd`:/io $(DOCKER_IMAGE) /io/.ci/linux-build.sh
        displayName: "Build"

      - script: |
          twine upload dist/* --config $(pypirc.secureFilePath)
        displayName: "Deploy"
